"""initial_schema

Revision ID: 626b47a8f364
Revises: 
Create Date: 2026-08-27 00:55:00.352279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626b47a8f364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_history')
    op.drop_index(op.f('idx_analysis_evidence_analysis'), table_name='analysis_evidence')
    op.drop_index(op.f('idx_analysis_evidence_target'), table_name='analysis_evidence')
    op.drop_index(op.f('idx_analysis_evidence_type'), table_name='analysis_evidence')
    op.drop_table('analysis_evidence')
    op.drop_index(op.f('idx_analysis_outcome_analysis'), table_name='analysis_outcome')
    op.drop_table('analysis_outcome')
    op.drop_index(op.f('idx_entries_category'), table_name='entries')
    op.drop_index(op.f('idx_entries_fetched'), table_name='entries')
    op.drop_index(op.f('idx_entries_hash'), table_name='entries')
    op.drop_index(op.f('idx_entries_published'), table_name='entries')
    op.drop_index(op.f('idx_entries_source'), table_name='entries')
    op.drop_index(op.f('idx_entry_analysis_entry'), table_name='entry_analysis')
    op.drop_index(op.f('idx_entry_analysis_velocity'), table_name='entry_analysis')
    op.drop_column('entry_analysis', 'evidence_version')
    op.drop_column('entry_analysis', 'overall_confidence')
    op.drop_index(op.f('idx_fetch_log_source'), table_name='fetch_log')
    op.drop_index(op.f('idx_fetch_log_time'), table_name='fetch_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_fetch_log_time'), 'fetch_log', ['fetched_at'], unique=False)
    op.create_index(op.f('idx_fetch_log_source'), 'fetch_log', ['source_id'], unique=False)
    op.add_column('entry_analysis', sa.Column('overall_confidence', sa.REAL(), server_default=sa.text('(0.7)'), nullable=True))
    op.add_column('entry_analysis', sa.Column('evidence_version', sa.TEXT(), server_default=sa.text("'v1'"), nullable=True))
    op.create_index(op.f('idx_entry_analysis_velocity'), 'entry_analysis', ['threat_velocity'], unique=False)
    op.create_index(op.f('idx_entry_analysis_entry'), 'entry_analysis', ['entry_id'], unique=False)
    op.create_index(op.f('idx_entries_source'), 'entries', ['source_id'], unique=False)
    op.create_index(op.f('idx_entries_published'), 'entries', ['published_at'], unique=False)
    op.create_index(op.f('idx_entries_hash'), 'entries', ['content_hash'], unique=False)
    op.create_index(op.f('idx_entries_fetched'), 'entries', ['fetched_at'], unique=False)
    op.create_index(op.f('idx_entries_category'), 'entries', ['category'], unique=False)
    op.create_table('analysis_outcome',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('analysis_id', sa.TEXT(), nullable=False),
    sa.Column('outcome_type', sa.TEXT(), nullable=False),
    sa.Column('outcome_value', sa.TEXT(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("outcome_type IN ('telegram_sent','user_dismissed','user_escalated','false_positive','confirmed')"),
    sa.ForeignKeyConstraint(['analysis_id'], ['entry_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_analysis_outcome_analysis'), 'analysis_outcome', ['analysis_id'], unique=False)
    op.create_table('analysis_evidence',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('analysis_id', sa.TEXT(), nullable=False),
    sa.Column('claim_type', sa.TEXT(), nullable=False),
    sa.Column('claim_target', sa.TEXT(), nullable=False),
    sa.Column('claim_value', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('evidence_json', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.Column('model_version', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("claim_type IN ('fact','inference','hypothesis','assumption','unknown')"),
    sa.CheckConstraint("method IN ('heuristic','llm','hybrid')"),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0'),
    sa.ForeignKeyConstraint(['analysis_id'], ['entry_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_analysis_evidence_type'), 'analysis_evidence', ['claim_type'], unique=False)
    op.create_index(op.f('idx_analysis_evidence_target'), 'analysis_evidence', ['claim_target'], unique=False)
    op.create_index(op.f('idx_analysis_evidence_analysis'), 'analysis_evidence', ['analysis_id'], unique=False)
    op.create_table('digest_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('period_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('period_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('entry_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('delivery_method', sa.TEXT(), nullable=True),
    sa.Column('delivery_status', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
