"""add_epistemic_tables

Revision ID: da4ca2059230
Revises: 626b47a8f364
Create Date: 2026-08-27 00:58:06.123156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4ca2059230'
down_revision: Union[str, Sequence[str], None] = '626b47a8f364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables already exist from manual creation, just add columns
    op.add_column('entry_analysis', sa.Column('overall_confidence', sa.Float(), server_default=sa.text('0.7'), nullable=False))
    op.add_column('entry_analysis', sa.Column('evidence_version', sa.String(length=20), server_default=sa.text("'v1'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_analysis', 'evidence_version')
    op.drop_column('entry_analysis', 'overall_confidence')
    op.drop_index(op.f('ix_analysis_outcome_analysis_id'), table_name='analysis_outcome')
    op.drop_table('analysis_outcome')
    op.drop_index(op.f('ix_analysis_evidence_analysis_id'), table_name='analysis_evidence')
    op.drop_table('analysis_evidence')
    # ### end Alembic commands ###
